config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'groups#index', as: :authenticated_root
    end
    
    unauthenticated do
      root 'splash#index', as: :unauthenticated_root
    end
  end  

  resources :groups, only: [:index, :new, :create, :show, :destroy] do
    resources :entities, only: [:index, :new, :create, :show, :destroy]
  end

  root "splash#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :entities, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :groups, dependent: :destroy
  has_many :entities, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_group
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /groups/:group_id/entities
  def index
    @entities = @group.entities.group_by { |entity| [entity.user_id, entity.group_id] }
    @totals = {}
    @entities.each do |(user_id, group_id), entities|
      @totals[[user_id, group_id]] = entities.sum(&:amount)
    end
  end

  # GET /groups/:group_id/entities/new
  def new
    @entity = @group.entities.build
  end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to group_entities_path(@entity.group_id), notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_entity
    @entity = @group.entities.find(params[:id])
  end

  def entity_params
    params.require(:entity).permit(:name, :amount, :user_id, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>" class="category-row">
  <p>
    <strong>Name:</strong>
    <%= entity.name %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= entity.amount %>
  </p>
</div>

app/views/entities/_form.html.erb
<%= form_with(model: entity, url: group_entities_path(@group), class: "form") do |form| %>

  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.hidden_field:group_id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entities/index.html.erb
<div class="container">
<div>
<div class="header">
  <div>
  <%= link_to "Back", groups_path, class: "back-btn" %>
</div>
  <h1>
    Transaction
  </h1>
</div>



  <% @entities.each do |(user_id, group_id), entities| %>
<div class="info">
<div class="user-group">
     <div class="bank">
           <%= image_tag "group.svg", width: "40px", height: "40px" %>

      <p> <%= Group.find(group_id).name %></p>
     </div>
</div>
      <p>  <%= number_to_currency(@totals[[user_id, group_id]]) %></p>
</div>
          <div class="category-container">
            <% entities.each do |entity| %>
             <div class="category-col">
              <%= render partial: "entity", locals: { entity: entity } %>
            </div>
            <% end %>
          </div>
  <% end %>
</div>

<div class="button-container">
<%= link_to new_group_entity_path(@group), class: "button" do %>
  <span>New Transaction</span>
<% end %>
</div>

app/views/entities/new.html.erb
<div class="container">
<div>
<div class="header">
  <div>
<%= link_to "Back", group_entities_path(@group), class: "back-btn" %>
</div>
  <h1>
    New transaction
  </h1>
</div>

<%= render "form", entity: @entity %>
</div>

app/views/groups/_form.html.erb
<%= form_with(model: group, class: "form") do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "Enter name" %>
  </div>

  <div>
    <%= form.file_field :icon, placeholder: "Select icon" %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<%= link_to group_path(group) + "/entities", class: "category-row" do %>
  <div class="icon-name">
    <% if group.icon.present? && Rails.application.assets_manifest.assets[group.icon].present? %>
      <%= image_tag group.icon %>
    <% else %>
      <%= image_tag "Dollar.png", width: "40px", height: "40px" %>
    <% end %>
    <h3><%= group.name %></h3>
  </div>
    <p>
    <strong>Total Amount:</strong>
    <%= number_to_currency(group.entities.sum(:amount)) %>
  </p>
<% end %>

app/views/groups/index.html.erb
<div class="container">
<div>
<div class="header">
  <h1>
    Categories
  </h1>
      <% if user_signed_in? %>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "back-btn" %>
      <% end %>
</div>

<div id="groups" class="category-container">
  <% @groups.each do |group| %>
  <div class="category-col">
      <%= render group %>
  </div>
  <% end %>
</div>
</div>

<div class="button-container">
<%= link_to new_group_path, class: "button" do %>
  <span>New Category</span>
<% end %>
</div>
</div>

app/views/groups/new.html.erb
<div class="container">
<div>
<div class="header">
  <div>
  <%= link_to "Back", groups_path, class: "back-btn" %>
</div>
  <h1>
    New group
  </h1>
</div>

<%= render "form", group: @group %>

<br>
</div>

app/views/groups/show.html.erb
<div class="container">
<div>
<div class="header">
<div>
  <%= link_to "Back", groups_path, class: "back-btn" %>
</div>
  <h1>
    Show Categories
  </h1>
</div>

<div id="groups" class="category-container">
  <div class="category-col">
     <%= render @group %>
     <%= @group.created_at %>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetAppRor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/splash/index.html.erb
<div class="splash-container">
  <div></div>


  <div class="logo-container">
    <h3>Transacation</h3>
  </div>


  <div class="auth-btn">
    <%= link_to 'Log in'.html_safe, new_user_session_path, class: 'log-in-btn' %>
    <%= link_to 'Sign up', new_user_registration_path,  class: 'sign-up-btn' %> 
  </div>
</div>